- name: Wait for ssh connection
  hosts: community.digitalocean.digitalocean
  gather_facts: false
  tasks:
    - name: Ensure ssh port open
      wait_for:
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python


- name: Install Python3, Docker, Docker-compose, PIP
  hosts: community.digitalocean.digitalocean
  become: yes
  gather_facts: False
  tasks:
    - name: Make sure Python3 and Docker are installed
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
          - python3-pip
        state: present
    # - name: Update all packages   
    #   yum:
    #     name: '*'
    #     state: latest
    - name: Download Docker
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{lookup('pipe','uname -s')}}-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x

- name: Start Docker and add user to Docker group
  hosts: community.digitalocean.digitalocean
  tasks:
  - name: Ensure docker is running
    systemd:
      name: docker
      state: started
  - name: Install docker python module
    pip:
      name: 
        - docker
        - docker-compose
  - name: Append docker group to blackays
    user:
      name: blackays
      groups: docker,adm
      append: yes
  - name: Reconnect to server session
    meta: reset_connection

- name: test docker pull
  hosts: community.digitalocean.digitalocean
  become: yes
  become_user: blackays
  tasks:
    - name: pull redis
      community.docker.docker_image:
        name: redis
        source: pull


- name: Start docker containers
  hosts: community.digitalocean.digitalocean
  vars_files:
    - project-vars
  # vars_prompt:
  #   - name: docker_password
  #     prompt: Enter password
  become: yes
  become_user: blackays
  tasks:
    - name: Copy docker-compose file to server
      copy:
        src: /home/nazar/Devops/ansible/bootcamp/project-docker/docker-compose.yaml
        dest: /home/blackays/docker-compose.yaml
    - name: Docker login
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: blackays
        password: "{{docker_password}}"
    - name: Start containers from compose
      community.docker.docker_compose:
        project_src: /home/blackays
        state: present #docker-compose up (absent for down)